### ISSUE TITLE
Could not parse path '//rc' - misleading log message when non-Cromwell caller

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#161]
**Describe the bug**
`Could not parse path '//rc'.` error in the logs when a TES task is submitted from a non-Cromwell system

**Steps to Reproduce**
`{"executors":[{"image":"ubuntu:22.04","command":["echo","hello"]}]}`

**Expected behavior**
No log message for this scenario; we can assume it's a non-Cromwell system

**Comment by BMurri** [comment]
This line is relevant to this issue: [`var cromwellRcContent = await this.storageAccessProvider.DownloadBlobAsync($"/{GetCromwellExecutionDirectoryPath(tesTask)}/rc"`);](https://github.com/microsoft/ga4gh-tes/blob/94451a2af8c7d538e6740b95817acf959901d7fc/src/TesApi.Web/BatchScheduler.cs#L1702)

So is this one: [`//TODO: refactor this to throw an exception instead of logging and error and returning null.`](https://github.com/microsoft/ga4gh-tes/blob/55a850d9e76a74be7bb75a7ae6ea2fff63587c3f/src/TesApi.Web/Storage/DefaultStorageAccessProvider.cs#L98)

Please consider this: at this point, it would be a breaking change to simply start throwing exceptions from DefaultStorageAccessProvider.MapLocalPathToSasUrlAsync(), because too much code now depends on the current behavior. But, there's no reason throwing an exception couldn't be an opt-in, where the exception message would be what would have been logged. That way, the caller, who as the context to determine if this is something important or not, can make that determination.

**Comment by MattMcL4475** [comment]
@MattMcL4475 test to see if fixed in 4.6
