### ISSUE TITLE
Research if Docker pulls images before the start task runs

### ISSUE THREAD

**Issue by MattMcL4475** [microsoft/ga4gh-tes#370]
Currently, when using a private ACR, Batch is responsible for authenticating and pulling the images.  It's currently unknown whether that is happening before or after the start task runs.  This issue is to research the answer to this.

If the answer is that it is pulling the images before the start task, this is problematic for nodes that have a resource disk, because the start task won't have modified the Docker configuration to ensure that images are stored on the resource disk, potentially leading to a disk full.

If the answer is that it is pulling the images before the start task, we should likely implement something like this: https://github.com/microsoft/ga4gh-tes/issues/209 (however, this should be designed as a team first)

**Comment by giventocode** [comment]
I am wondering if this is required given that the idea is that that runner would be responsible of executing the docker command , authenticating with ACR and downloading images as needed (#151 and #279). Note that the runner should configure the docker settings required before the execution and pull (#363) . This approach guarantees that the correct data disk is used and we have full control of the lifecycle of the images.

**Comment by MattMcL4475** [comment]
@giventocode this issue is primarily to determine if the current implementation has an issue as-is, in order to prioritize a new implementation like you describe (or #209).

**Comment by BMurri** [comment]
I ran a test where I configured a pool on a batch account to provide the authentication to a non-anonymous container registry, and provided a start task with the following command line: `docker image list` The following was returned:

> REPOSITORY    TAG       IMAGE ID       CREATED        SIZE
> ubuntu        22.04     01f29b872827   3 weeks ago    77.8MB
> hello-world   latest    9c7a54a9a43c   3 months ago   13.3kB 

Conclusion: for current private networking (or any other use of a non-anonymous registry) we will require either installing and using `az-cli` to log into the container registries, or task the node task runner with authentication. Basically, due to the issue that produced this issue, non-anonymous container registry access is broken for all cases where we are not using gen1 images exclusively.
